# Generated by Django 4.2.3 on 2023-10-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('tile_quantity', models.PositiveBigIntegerField()),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tile')),
            ],
        ),
    ]
